#!/bin/sh -e
interface=$1
# paths to state file and definition dir
PState=/var/fsm/$3-$interface
PDef=/lib/fsm/$3

. /lib/fsm/fsm-common.sh

fail() {
    echo "$1" 1>&2
    exit 1
}

printArgs () {
    fail "Usage:
$0 uci-interface get    fsm
$0 uci-interface watch  fsm
$0 uci-interface change fsm state"
}

[ $# -lt 3 ] && printArgs

# check for minimal FSM definition
if [   -f $PDef/initial_state \
    -a -d $PDef/watch \
    -a -d $PDef/trans ]; then
    if [ ! -f $PState ]; then
	mkdir -p $(dirname $PState)
	S=$(cat $PDef/initial_state)
	[ -n "$S" ] || fail "initial state must not be empty"
	echo $S >$PState
    fi
else
    fail "FSM $3 does not exist"
fi

case "$2" in
    get)
	cat $PState
	;;
    watch)
	lockState $PState
	watch $PState $PDef $interface
	;;
    change)
	[ -n "$4" ] || printArgs
	lockState $PState
	change $PState $PDef $4 $interface
	;;
    *)
	printArgs
esac