#!/bin/sh
scriptname=$(basename $0)
pidfile=$1
iface=$2
interface=$3
logfile=/tmp/netifd-fsm-$interface.log

# Common FSM functions
. /lib/fsm/fsm-common.sh

fsm_list=$(uci -q get fsm.$interface.fsm_list)
gossip_list=$(uci -q get fsm.$interface.gossip_list)

logmessage() {
	local timestamp=$(date +"%Y-%m-%d %H:%M:%S")
	if [ "$(ls -l $logfile | awk '{print $5}')" -ge 100000 ]; then
		logger -t netifd-fsm "[$interface]: Logfile of 100kb limit reached. Rotating log"
		echo "$timestamp - netifd-fsm [$interface]: Logfile of 100kb limit reached. Rotating log" 1>> "$logfile"
		[ -f "$logfile.1.gz" ] && rm -f "$logfile.1.gz"
		mv $logfile $logfile.1
		gzip $logfile.1
	fi
	logger -t netifd-fsm "[$interface]: $1"
	echo "$timestamp - netifd-fsm [$interface]: $1" 1>> "$logfile"
}

#Overiding default fail function ;)
fail() {
    logmessage "[FAILURE]: $1" 1>&2
    exit 1
}

[ $# -lt 3 ] && fail "Has to be run by netifd!"

if [ -e $pidfile ]; then
	pid=`cat $pidfile`
	if [ -d /proc/$pid ]; then
		fail "Already running"
	else
		rm $pidfile
	fi
fi
echo $$ > $pidfile
# Create p2ptbl folder if not existant
[ ! -d /var/p2ptbl/$interface ] && mkdir -p /var/p2ptbl/$interface
# Remove old PState file(s) for this interface
rm -f /var/fsm/*-$interface

# Create config cache folders if none existant or clear the cache
for fsm in $(echo $fsm_list)
do
	if [ ! -d /var/$fsm/$interface/ ]; then
		mkdir -p /var/$fsm/$interface/
	else
		rm -f /var/$fsm/$interface/*
	fi
done

# Remove dnsmasq.conf if exists, FSM will create a symlink to /tmp for dynamic configuration without writing changes to uci config files
if [ ! -h /etc/dnsmasq.conf ]; then
	# Remove config if existant
	[ -f /etc/dnsmasq.conf ] && rm -f /etc/dnsmasq.conf
	touch /tmp/dnsmasq.conf
	ln -s /tmp/dnsmasq.conf /etc/dnsmasq.conf
	cat <<EOF > /tmp/dnsmasq.conf
dhcp-hostsfile=/tmp/dhcp.hostconfig

EOF
elif [ -s /tmp/dnsmasq.conf ]; then
	# Remove old interface settings from file
	sed \
    -e "/$interface settings/d" \
    -i "/tmp/dnsmasq.conf"
else 
	cat <<EOF > /tmp/dnsmasq.conf
dhcp-hostsfile=/tmp/dhcp.hostconfig

EOF
fi

# Remove /etc/resolv.conf link if it doesn't point to /tmp/resolv.conf.auto
# We will be using only remote DNS servers for local querries.

if [ $(readlink /etc/resolv.conf) == "/tmp/resolv.conf" ]; then
	rm -f /etc/resolv.conf
	ln -s /tmp/resolv.conf.auto /etc/resolv.conf
fi

logmessage "Restarting dnsmasq to make sure old settings are no longer active"
/etc/init.d/dnsmasq restart || true

logmessage "Starting netifd-fsm daemon"
while true; do
	for fsm in $(echo $fsm_list)
	do
		PState=/var/fsm/$fsm-$interface
		PDef=/lib/fsm/$fsm
		if [   -f $PDef/initial_state \
			-a -d $PDef/watch \
			-a -d $PDef/trans ]; then
			if [ ! -f $PState ]; then
				mkdir -p $(dirname $PState)
				S=$(cat $PDef/initial_state)
				[ -n "$S" ] || fail "fsm $fsm: initial state must not be empty"
				echo $S >$PState
			fi
		else
			fail "FSM $fsm does not exist"
		fi
		logmessage "Calling 'watch $PState $PDef $interface'"
		watch $PState $PDef $interface
	done
	for gossip in $gossip_list
	do
		table=/var/p2ptbl/$interface/$gossip
		[ ! -f $table ] && p2ptbl init  $table
		logmessage "Gossiping p2ptable $gossip on interface $interface"
		p2ptbl gossip $table 500 $iface
	done
	#Currently Hardcoded Interval, whole code needs to be changed into something parallel with individual sleep cycles
	sleep 60
done